language: objective-c
os: osx
script: 
  - xcodebuild -workspace InAppSettingsKit.xcworkspace -scheme InAppSettingsKitFramework build | xcpretty
  - xcodebuild -workspace InAppSettingsKit.xcworkspace -scheme InAppSettingsKit -destination platform\=iOS\ Simulator,OS\=10.1,name\=iPhone\ 6s build test | xcpretty
  - xcodebuild -workspace InAppSettingsKit.xcworkspace -scheme Sample\ App build | xcpretty
