language: objective-c
os: osx
xcode_workspace: InAppSettingsKit.xcworkspace
xcode_destination: platform=iOS Simulator,OS=10.1,name=iPhone 6s
matrix:
  include:
    - stage: Static Library & Tests
      xcode_scheme: InAppSettingsKit
    - stage: Framework
      script:
        - xcodebuild -workspace InAppSettingsKit.xcworkspace -scheme InAppSettingsKitFramework build | xcpretty
    - stage: Sample App
      script:
        - carthage bootstrap --cache-builds
